//
//  BookDetailsInteractor.swift
//  ITBookStore
//
//  Created by Bakur Khalvashi on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailsBusinessLogic
{
  func doSomething(request: BookDetails.Something.Request)
}

protocol BookDetailsDataStore
{
  //var name: String { get set }
}

class BookDetailsInteractor: BookDetailsBusinessLogic, BookDetailsDataStore
{
  var presenter: BookDetailsPresentationLogic?
  var worker: BookDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BookDetails.Something.Request)
  {
    worker = BookDetailsWorker()
    worker?.doSomeWork()
    
    let response = BookDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
