//
//  BookDetailsPresenter.swift
//  ITBookStore
//
//  Created by Bakur Khalvashi on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailsPresentationLogic
{
  func presentSomething(response: BookDetails.Something.Response)
}

class BookDetailsPresenter: BookDetailsPresentationLogic
{
  weak var viewController: BookDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: BookDetails.Something.Response)
  {
    let viewModel = BookDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
